// Copyright (c) 2015-2022 MinIO, Inc.
//
// This file is part of MinIO Object Storage stack
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package cmd

import (
	"runtime"
	"strconv"
	"time"
)

// upstreamCopyrightEndYear is the last year of upstream MinIO, Inc. development
// this fork derives from. It is fixed: the fork's own maintenance does not
// extend the upstream copyright term.
const upstreamCopyrightEndYear = "2025"

// forkCopyrightStartYear is the year the Silo fork began.
const forkCopyrightStartYear = "2025"

// copyrightEndYear returns the end year shown in copyright notices for the
// fork's own modifications. Release builds inject CopyrightYear through
// ldflags; source builds keep the "0000" placeholder, for which the current
// year is used instead.
func copyrightEndYear() string {
	if CopyrightYear == "" || CopyrightYear == "0000" {
		return strconv.Itoa(time.Now().Year())
	}
	return CopyrightYear
}

// DO NOT EDIT THIS FILE DIRECTLY. These are build-time constants
// set through ‘buildscripts/gen-ldflags.go’.
var (
	// GOPATH - GOPATH value at the time of build.
	GOPATH = ""

	// GOROOT - GOROOT value at the time of build.
	GOROOT = ""

	// Version - version time.RFC3339.
	Version = "DEVELOPMENT.GOGET"

	// ReleaseTag - release tag in TAG.%Y-%m-%dT%H-%M-%SZ.
	ReleaseTag = "DEVELOPMENT.GOGET"

	// CommitID - latest commit id.
	CommitID = "DEVELOPMENT.GOGET"

	// ShortCommitID - first 12 characters from CommitID.
	ShortCommitID = "DEVELOPMENT.GOGET"

	// CopyrightYear - dynamic value of the copyright end year
	CopyrightYear = "0000"

	// MinioReleaseTagTimeLayout - release tag time layout.
	MinioReleaseTagTimeLayout = "2006-01-02T15-04-05Z"

	// MinioOSARCH - OS and ARCH.
	minioOSARCH = runtime.GOOS + "-" + runtime.GOARCH

	// MinioReleaseBaseURL is retained for source compatibility. Silo does not
	// provide an in-place update endpoint.
	MinioReleaseBaseURL = ""

	// MinioReleaseURL - release URL.
	MinioReleaseURL = MinioReleaseBaseURL + minioOSARCH + SlashSeparator

	// MinioStoreName - Silo product name. The identifier is retained to avoid a
	// source-only rename across compatibility-sensitive code.
	MinioStoreName = "Silo"

	// MinioUAName - Silo user agent name.
	MinioUAName = "Silo"

	// MinioBannerName - Silo banner name for startup message.
	MinioBannerName = "Silo Object Storage Server"

	// MinioLicense - MinIO server license.
	MinioLicense = "GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html"
)
